version: '2'

services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile-webapp
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=abc123
    networks:
      - ctf_net
  mysql:
    image: mysql:latest
    networks:
      - ctf_net
    environment:
      MYSQL_ROOT_PASSWORD: abc123

networks:
  ctf_net:
    driver: bridge